# Generated by Django 3.1.7 on 2021-05-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=128, null=True)),
                ('intro', models.CharField(blank=True, db_column='INTRO', max_length=1024, null=True)),
                ('estab_date', models.DateField(blank=True, db_column='ESTAB_DATE', null=True)),
                ('year_number', models.IntegerField(blank=True, db_column='YEAR_NUMBER', null=True)),
                ('crated_by', models.CharField(blank=True, db_column='CRATED_BY', max_length=32, null=True)),
                ('crated_time', models.DateTimeField(blank=True, db_column='CRATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=128, null=True)),
                ('short_name', models.CharField(blank=True, db_column='SHORT_NAME', max_length=128, null=True)),
                ('intro', models.CharField(blank=True, db_column='INTRO', max_length=512, null=True)),
                ('president', models.CharField(blank=True, db_column='PRESIDENT', max_length=32, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_college',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=128, null=True)),
                ('intro', models.CharField(blank=True, db_column='INTRO', max_length=512, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_lesson',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=128, null=True)),
                ('short_name', models.CharField(blank=True, db_column='SHORT_NAME', max_length=128, null=True)),
                ('estab_date', models.DateField(blank=True, db_column='ESTAB_DATE', null=True)),
                ('intro', models.CharField(blank=True, db_column='INTRO', max_length=512, null=True)),
                ('tuition_fee', models.CharField(blank=True, db_column='TUITION_FEE', max_length=32, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_major',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=128, null=True)),
                ('short_name', models.CharField(blank=True, db_column='SHORT_NAME', max_length=128, null=True)),
                ('intro', models.CharField(blank=True, db_column='INTRO', max_length=512, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_organization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=32, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
                ('college_id', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.college')),
            ],
            options={
                'db_table': 'ego_teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('intro', models.CharField(blank=True, db_column='INTRO', max_length=512, null=True)),
                ('entry_date', models.DateField(blank=True, db_column='ENTRY_DATE', null=True)),
                ('status', models.IntegerField(blank=True, db_column='STATUS', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.class')),
                ('college_id', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.college')),
                ('organization_id', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.organization')),
            ],
            options={
                'db_table': 'ego_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Selclass',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.class')),
                ('lesson_id', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.student')),
            ],
            options={
                'db_table': 'ego_selclass',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.class')),
                ('lesson_id', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.teacher')),
            ],
            options={
                'db_table': 'ego_instruct',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='class',
            name='college_id',
            field=models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.college'),
        ),
        migrations.AddField(
            model_name='class',
            name='major_id',
            field=models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.CASCADE, to='lesson.major'),
        ),
    ]
