# Generated by Django 3.1.7 on 2021-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True),
        ),
    ]
