# Generated by Django 3.1.7 on 2021-06-03 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210602_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(blank=True, db_column='ROLE_ID', null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=32, null=True)),
                ('assign_id', models.CharField(blank=True, db_column='ASSIGN_ID', max_length=32, null=True)),
                ('assign_time', models.DateTimeField(blank=True, db_column='ASSIGN_TIME', null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ego_role',
                'managed': True,
            },
        ),
    ]
