# Generated by Django 3.1.7 on 2021-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('problem_id', models.CharField(db_column='PROBLEM_ID', max_length=32)),
                ('puid', models.CharField(blank=True, db_column='PUID', max_length=32, null=True)),
                ('name', models.CharField(db_column='NAME', max_length=128)),
                ('problem_decription', models.TextField(blank=True, db_column='PROBLEM_DECRIPTION', null=True)),
                ('module_decription', models.TextField(blank=True, db_column='MODULE_DECRIPTION', null=True)),
                ('input_decription', models.TextField(blank=True, db_column='INPUT_DECRIPTION', null=True)),
                ('output_decription', models.TextField(blank=True, db_column='OUTPUT_DECRIPTION', null=True)),
                ('test_decription', models.CharField(blank=True, db_column='TEST_DECRIPTION', max_length=32, null=True)),
                ('difficulty', models.IntegerField(blank=True, db_column='DIFFICULTY', null=True)),
                ('resource_limit', models.DecimalField(blank=True, db_column='RESOURCE_LIMIT', decimal_places=10, max_digits=32, null=True)),
                ('freq_limit', models.DecimalField(blank=True, db_column='FREQ_LIMIT', decimal_places=10, max_digits=32, null=True)),
                ('power_limit', models.DecimalField(blank=True, db_column='POWER_LIMIT', decimal_places=10, max_digits=32, null=True)),
                ('public_status', models.IntegerField(blank=True, db_column='PUBLIC_STATUS', null=True)),
                ('platform', models.IntegerField(blank=True, db_column='PLATFORM', null=True)),
                ('publish_status', models.IntegerField(blank=True, db_column='PUBLISH_STATUS', null=True)),
                ('pcateory', models.CharField(blank=True, db_column='PCATEORY', max_length=1024, null=True)),
                ('ptag', models.CharField(blank=True, db_column='PTAG', max_length=1024, null=True)),
                ('source', models.CharField(blank=True, db_column='SOURCE', max_length=1024, null=True)),
                ('online_testbench', models.CharField(blank=True, db_column='ONLINE_TESTBENCH', max_length=1024, null=True)),
                ('online_testbench_md5', models.CharField(blank=True, db_column='ONLINE_TESTBENCH_MD5', max_length=128, null=True)),
                ('board_testbench', models.CharField(blank=True, db_column='BOARD_TESTBENCH', max_length=1024, null=True)),
                ('board_testbench_md5', models.CharField(blank=True, db_column='BOARD_TESTBENCH_MD5', max_length=128, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_problem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ptag',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=32, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=32, null=True)),
                ('created_time', models.DateTimeField(blank=True, db_column='CREATED_TIME', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=32, null=True)),
                ('updated_time', models.DateTimeField(blank=True, db_column='UPDATED_TIME', null=True)),
            ],
            options={
                'db_table': 'ego_ptag',
                'managed': True,
            },
        ),
    ]
