# Generated by Django 3.1.7 on 2021-05-28 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poprecord',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drecord',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='problem.device'),
        ),
    ]
